__all__  = ['FRONT_LEFT_ENCODER_REVERSE_CYCLE', 'FRONT_RIGHT_ENCODER_REVERSE_CYCLE', 'BACK_LEFT_ENCODER_REVERSE_CYCLE', 'BACK_RIGHT_ENCODER_REVERSE_CYCLE', 
            'FRONT_LEFT_ENCODER_FORWARD_CYCLE', 'FORNT_RIGHT_ENCODER_FORWARD_CYCLE', 'BACK_LEFT_ENCODER_FORWARD_CYCLE', 'BACK_RIGHT_ENCODER_REVERSE_CYCLE',
            'WHEEL_RADIUS', 'WHEEL_GAP']


WHEEL_RADIUS = 0.03
WHEEL_GAP = 0.19

FRONT_LEFT_ENCODER_REVERSE_CYCLE = 3028
FRONT_RIGHT_ENCODER_REVERSE_CYCLE = 4500
BACK_LEFT_ENCODER_REVERSE_CYCLE = 8470
BACK_RIGHT_ENCODER_REVERSE_CYCLE = 1538

FRONT_LEFT_ENCODER_FORWARD_CYCLE = 3010
FRONT_RIGHT_ENCODER_FORWARD_CYCLE = 4990
BACK_LEFT_ENCODER_FORWARD_CYCLE = 8222 
BACK_RIGHT_ENCODER_FORWARD_CYCLE = 2776

